### PR TITLE
KS-9/ Setting up i18n 

### PR DESCRIPTION
**Pull request by shrijan00003**
- i18n setup completed still need to figure it out using backend plugin

### CODE REVIEW

**Comment by shrijan00003** [comment]
@akasrai this seems like a hack on the rule of i18n, I think for modularity we have to create namespaces and use that with Backend plugin that I have already installed. 

I have got the problem with the code of using Backend plugin using documentation, let me know if there is any fixes for it.

**Comment by shrijan00003** [comment]
@akasrai  
- good news: kept in the public folder and used Backend plugin for fetching translation file works perfectly
- The bad one: need one more XHR call to the public forgetting transalation.json file and we need to wrap the component either with the suspense or we have to wait for the response from XHR request otherwise the raw text will be shown at the first and then translated one.

**Comment by akasrai** [comment]
The XHR request isn't expensive, we can always use suspense with message to users, here's one example `https://firmpayments.com`. But,  `i18next-http-backend` is deprecated. So, we have to look for replacement or lets go the old way keeping locale inside  `src`.

**Comment by shrijan00003** [comment]
> The XHR request isn't expensive, we can always use suspense with message to users, here's one example `https://firmpayments.com`. But, `i18next-http-backend` is deprecated. So, we have to look for replacement or lets go the old way keeping locale inside `src`.

ok as your wish 👍  we can always refactor :)

**Review by akasrai — APPROVED** [review]

**Pull request merged**
